#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := mrubyc-esp32

# include
include $(IDF_PATH)/make/project.mk
include sdkconfig

# command
MRBC = mrbc
MAKE = make
ESPTOOL = esptool.py
FLASH_FIRMWARE_CMD=$(shell make print_flash_cmd)
MKSPIFFS=$(shell which mkspiffs|xargs -I@ basename @)
SPIFFS_DATA_OFFSET=$(shell awk '/spiffs/ {print $$0}' partitions.csv| cut -d , -f 4)
SPIFFS_DATA_TABLE_SIZE=$(shell awk '/spiffs/ {print $$0}' partitions.csv| cut -d , -f 5)

gems:
	python bin/make-gems.py

gems-clean:
	python bin/clean-gems.py

.PHONY: spiffs

spiffs:
	$(MRBC) -o ./spiffs/mrbc/master.mrbc -E ./mrblib/master.rb
ifeq ($(CONFIG_ENABLE_MULTITASK),y)
	$(MRBC) -o ./spiffs/mrbc/slave.mrbc -E ./mrblib/slave.rb
else
	rm -f ./spiffs/mrbc/slave.mrbc
endif
	$(MKSPIFFS) -c ./spiffs/mrbc -p 256 -b 4096 -s $(SPIFFS_DATA_TABLE_SIZE) ./spiffs/mrbc.spiffs.bin
	$(ESPTOOL) --chip esp32 --baud 921600 --port $(CONFIG_ESPTOOLPY_PORT) --before default_reset --after hard_reset write_flash -z --flash_mode qio --flash_freq 80m --flash_size detect $(SPIFFS_DATA_OFFSET) ./spiffs/mrbc.spiffs.bin
